# 01-1 연습문제

Numpy의 ndarray를 활용하여
1. 정수 10, 20, 30, 40, 50으로 구성된 배열을 생성하고,
2. 배열의 길이(원소 개수)를 출력하며,
3. 배열의 첫 번째 원소와 마지막 두 개 원소를 각각 출력하고,
4. for문과 enumerate()를 이용해 인덱스와 값을 함께 출력하시오.

In [2]:
import numpy as np

In [5]:
myarray=np.array([10,20,30,40,50])

print('배열의 길이: %d'%len(myarray))
print('첫 번째 원소: %d'%myarray[0])
print('마지막 두 개 원소:',myarray[-2:])

for i, v in enumerate(myarray):
    print('%d번째 원소 >> %d'%(i,v))

배열의 길이: 5
첫 번째 원소: 10
마지막 두 개 원소: [40 50]
0번째 원소 >> 10
1번째 원소 >> 20
2번째 원소 >> 30
3번째 원소 >> 40
4번째 원소 >> 50


# 01-2 연습문제

학생 6명의 점수 데이터가 다음과 같이 주어집니다.  
score=[72.5, 88.0, 91.5, 67.0, 80.0, 59.5]

1. 위 점수 리스트를 정수형 ndarray로 변환하시오.
2. 점수가 80점 이상인 학생의 점수만 추출하여 출력하시오.
3. 모든 학생에게 다음 기준으로 학점을 부여하고 결과를 출력하시오.
    - 90점 이상 -> 'A'
    - 80점 이상 -> 'B'
    - 70점 이상 -> 'C'
    - 그 외 -> 'F'

In [3]:
import numpy as np

In [7]:
score=[72.5, 88.0, 91.5, 67.0, 80.0, 59.5]

myscore=np.array(score,dtype='int')
print('원본 점수:',myscore)

print('80점 이상:',myscore[myscore>=80])

conditions=[(myscore>=90),
            (myscore>=80),
            (myscore>=70)]
value=['A','B','C']

print('학점 결과:',np.select(conditions,value,default='F'))

원본 점수: [72 88 91 67 80 59]
80점 이상: [88 91 80]
학점 결과: ['C' 'B' 'A' 'F' 'B' 'F']


# 01-3 연습문제

당신은 AI 교육기관에서 수강생들의 모의시험 데이터를 검수하는 일을 맡고 있습니다.  
시험 데이터는 '3회차 시험 * 4명 학생'의 점수로 구성되어야 합니다.  
다음 조건에 맞게 NumPy로 코드를 작성하세요.

1. 평균이 75, 표준편차가 5인 정규분포를 따르는 랜덤 점수 데이터를 3행 4열 배열로 생성하시오.
    - 단, 결과가 재현되도록 랜덤 시드를 100으로 고정해야 함.
2. 생성된 점수 중 80점 이상인 항목만 추출하시오.
3. 점수가 저장된 배열의 차원(ndim), 형태(shape), 데이터 타입(dtype)을 각각 출력하시오.

In [8]:
import numpy as np

In [12]:
np.random.seed(100)
score=np.random.normal(75,5,(3,4))
print(score)

print('80점 이상 점수:',score[score>=80])
print('차원:',score.ndim)
print('형태:',score.shape)
print('데이터 타입:',score.dtype)

[[66.25117263 76.71340202 80.76517901 73.73781982]
 [79.90660393 77.57109421 76.10589835 69.64978335]
 [74.05252085 76.27500722 72.70986507 77.17581744]]
80점 이상 점수: [80.76517901]
차원: 2
형태: (3, 4)
데이터 타입: float64


# 01-4 연습문제

아래 조건에 따라 NumPy를 이용해 데이터 타입과 구조를 정리하세요.

1. 0부터 11까지의 정수를 가지는 배열을 생성하시오.
2. 이 배열을 실수형(float)으로 변환하시오.
3. 변환된 배열을 2행 6열 구조로 재배치하시오.
4. 이후, 열의 수에 관계없이 3행으로 자동 변환되도록 reshape() 함수를 이용하시오.
5. 마지막으로, 1차원 배열로 축소하여 결과를 출력하시오.

In [13]:
import numpy as np

In [23]:
arr1=np.arange(12)
print('원본 배열:',arr1)

arr2=arr1.astype('float')
print('실수형 변환:',arr2)

arr3=arr2.reshape(2,6)
print('2행 6열 형태:')
print(arr3)

arr4=arr3.reshape(3,-1)
print('자동 계산된 형태(3행, 4열):')
print(arr4)

arr5=arr4.reshape(-1)
print('1차원 배열로 축소:')
print(arr5)

원본 배열: [ 0  1  2  3  4  5  6  7  8  9 10 11]
실수형 변환: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
2행 6열 형태:
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]]
자동 계산된 형태(3행, 4열):
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
1차원 배열로 축소:
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


# 01-5 연습문제

두 팀, 'Alpha'와 'Bravo'의 게임 점수 데이터가 주어졌을 때, 각 팀 점수에 대한 기초 통계량을 산출하세요.

'Alpha' 팀 점수 : [88,92,76,100,95,81,79,98,85,87]  
'Bravo' 팀 점수 : [65,99,78,72,80,91,75,82,89,70]

기초 통계량 -> 도수, 평균, 표준편차, 최소값, 1사분위수, 중위값, 3사분위수, 최대값

In [3]:
import numpy as np
from pandas import DataFrame

In [8]:
Alpha=[88,92,76,100,95,81,79,98,85,87]
Bravo=[65,99,78,72,80,91,75,82,89,70]

mydata={
    'alpha':{
        '도수':len(Alpha),
        '평균':np.average(Alpha),
        '표준편차':np.std(Alpha),
        '최소값':np.min(Alpha),
        '1사분위 수':np.quantile(Alpha,0.25),
        '중위값':np.median(Alpha),
        '3사분위 수':np.quantile(Alpha,0.75),
        '최대값':np.max(Alpha)
    },
    'bravo':{
        '도수':len(Bravo),
        '평균':np.average(Bravo),
        '표준편차':np.std(Bravo),
        '최소값':np.min(Bravo),
        '1사분위 수':np.quantile(Bravo,0.25),
        '중위값':np.median(Bravo),
        '3사분위 수':np.quantile(Bravo,0.75),
        '최대값':np.max(Bravo)
    }
}

df=DataFrame(mydata)
df

alpha      bravo
도수       10.00  10.000000
평균       88.10  80.100000
표준편차      7.70   9.924213
최소값      76.00  65.000000
1사분위 수   82.00  72.750000
중위값      87.50  79.000000
3사분위 수   94.25  87.250000
최대값     100.00  99.000000

# 01-6 연습문제

주어진 데이터를 사용하여 판매량 분포를 파악하고, 아래 요구사항에 따라 분석 결과를 출력하는 Python 콛즈를 작성하세요.  
- 일일 판매량 데이터
    [18,25,33,21,28,40,15,3,9,17,22,29,38,45,11,6,31,24,27,35,12,19,39,42,7,2,20,34,26,30]
- 요구사항
    1. 주어진 일일 판매량 데이터를 'numpy'배열로 생성하세요.
    2. 판매량 구간을 '[0,10,20,30,40,50]'으로 직접 설정하여 도수분포를 분석하세요.
    3. 2번의 도수 분포표를 활용하여 절대도수, 상대도수, 누적도수를 포함하는 도수 분포표를 출력하세요.
        - 상대도수는 소수점 넷째 자리에서 반올림하여 셋째 자리까지 표시하세요.

In [1]:
import numpy as np
from pandas import DataFrame

In [14]:
mydata=np.array([18,25,33,21,28,40,15,3,9,17,22,29,38,45,11,6,31,24,27,35,12,19,39,42,7,2,20,34,26,30])
myarray=[0,10,20,30,40,50]
hist,bins=np.histogram(mydata,myarray)
count=0
# 도수분포표
s=len(hist)
for i in range(0,s):
    if i+1<s:
        tpl='%d이상 %d미만: 절대도수(%d), 상대도수(%0.3f), 누적도수(%d)'
    else:
        tpl='%d이상 %d이하: 절대도수(%d), 상대도수(%0.3f), 누적도수(%d)'
    print(tpl%(bins[i],bins[i+1],hist[i],(hist[i]/np.sum(hist)),count+hist[i]))
    count+=hist[i]

0이상 10미만: 절대도수(5), 상대도수(0.167), 누적도수(5)
10이상 20미만: 절대도수(6), 상대도수(0.200), 누적도수(11)
20이상 30미만: 절대도수(9), 상대도수(0.300), 누적도수(20)
30이상 40미만: 절대도수(7), 상대도수(0.233), 누적도수(27)
40이상 50이하: 절대도수(3), 상대도수(0.100), 누적도수(30)
