# 라이브러리 참조

In [1]:
import numpy as np

# 배열 생성

In [2]:
arr=np.array([1,3,5,7,9])
print(type(arr))
arr

<class 'numpy.ndarray'>


array([1, 3, 5, 7, 9])

# 배열의 크기

In [3]:
arr=np.array([10,30,50,70,90])
size=len(arr)
print('배열의 원소는 %d개 입니다.'%size)

배열의 원소는 5개 입니다.


# 배열의 인덱싱과 슬라이싱

In [4]:
mydata=np.array([5,10,15,20,25])

print(mydata[0])
print(mydata[1])
print(mydata[3])

print(mydata[1:4])
print(mydata[-4:-1])

5
10
20
[10 15 20]
[10 15 20]


# 반복문을 통한 활용

In [5]:
mydata=np.array([100,110,120,130,140])

for i,v in enumerate(mydata):
    print('%d번째 원소 >> %d'%(i,v))

0번째 원소 >> 100
1번째 원소 >> 110
2번째 원소 >> 120
3번째 원소 >> 130
4번째 원소 >> 140


# ndarray의 특성

In [6]:
mylist=[100,3.14,True]
mylist

[100, 3.14, True]

In [7]:
myarr=np.array(mylist)
myarr

array([100.  ,   3.14,   1.  ])