In [1]:
import numpy as np

# 배열의 타입

In [2]:
mylist1=[100.12,3.14,1.5]
myarr1=np.array(mylist1,dtype='int')
myarr1

array([100,   3,   1])

In [3]:
mylist2=[1.2,3,True,'4']
myarr2=np.array(mylist2)
myarr2

array(['1.2', '3', 'True', '4'], dtype='<U32')

In [4]:
mylist3=[10,20,30,40,50]
myarr3=np.array(mylist3)
print(type(myarr3),myarr3)

mylist3_1=list(myarr3)
print(type(mylist3_1),mylist3_1)

<class 'numpy.ndarray'> [10 20 30 40 50]
<class 'list'> [np.int64(10), np.int64(20), np.int64(30), np.int64(40), np.int64(50)]


# 배열의 연산

In [5]:
arr1=np.array([10,15,20,25,30])
arr2=np.array([2,3,4,5,6])
print(arr1)
print(arr2)

[10 15 20 25 30]
[2 3 4 5 6]


In [11]:
a1=arr1+arr2
print(a1)

a2=np.add(arr1,arr2)
print(a2)

[12 18 24 30 36]
[12 18 24 30 36]


In [12]:
b1=arr1-arr2
print(b1)

b2=np.subtract(arr1,arr2)
print(b2)

[ 8 12 16 20 24]
[ 8 12 16 20 24]


In [13]:
c1=arr1*arr2
print(c1)

c2=np.multiply(arr1,arr2)
print(c2)

[ 20  45  80 125 180]
[ 20  45  80 125 180]


In [14]:
d1=arr1/arr2
print(d1)

d2=np.divide(arr1,arr2)
print(d2)

[5. 5. 5. 5. 5.]
[5. 5. 5. 5. 5.]


# 배열의 조건식

In [15]:
grade=np.array([82,77,91,88])
grade

array([82, 77, 91, 88])

In [16]:
bool_array=np.array([True,False,True,False])
bool_array

array([ True, False,  True, False])

In [17]:
result1=grade[bool_array]
result1

array([82, 91])

In [18]:
mypoint=np.array([82,77,91,88])
ge80=mypoint[mypoint>=80]
ge80

array([82, 91, 88])

In [19]:
ge80le90=mypoint[np.logical_and(mypoint>=80,mypoint<=90)]
ge80le90

array([82, 88])

In [20]:
gt_or_lt=mypoint[np.logical_or(mypoint<80,mypoint>90)]
gt_or_lt

array([77, 91])

In [21]:
exam=np.array([60,83,75,92,86])
result=np.where(exam>=80,'합격','불합격')
result

array(['불합격', '합격', '불합격', '합격', '합격'], dtype='<U3')

In [22]:
exam=np.array([60,85,51,79,94,88])

conditions=[(exam>=90),
            (exam>=80),
            (exam>=70)]
value=['A','B','C']

result=np.select(conditions,value,default='F')
result

array(['F', 'B', 'F', 'C', 'A', 'B'], dtype='<U1')