In [1]:
import numpy as np

# 2차원 배열의 정보 확인 및 검색

In [2]:
myarray=np.array([
    [98,72,80,64],
    [88,90,80,72],
    [92,88,82,76]
])

print(myarray)

print('차원크기:',myarray.ndim)
print('차원별 원소수:',myarray.shape)
print('원소의 데이터 타입:',myarray.dtype)

[[98 72 80 64]
 [88 90 80 72]
 [92 88 82 76]]
차원크기: 2
차원별 원소수: (3, 4)
원소의 데이터 타입: int64


In [3]:
bool_array=np.array([
    [True, False, True, False],
    [True, True, True, False],
    [True, True, True, False]
])

result1=myarray[bool_array]
result1

array([98, 80, 88, 90, 80, 92, 88, 82])

In [4]:
result2=myarray[myarray>=80]
result2

array([98, 80, 88, 90, 80, 92, 88, 82])

In [5]:
result3=myarray[np.logical_and(myarray>=80,myarray<=90)]
result3

array([80, 88, 90, 80, 88, 82])

In [6]:
result4=myarray[np.logical_or(myarray<80,myarray>90)]
result4

array([98, 72, 64, 72, 92, 76])

# 정영화된 배열 생성

In [7]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.full([3,4],10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# 랜덤 배열

In [11]:
np.random.rand(10)

array([0.03151106, 0.89082774, 0.03262982, 0.99671153, 0.85560547,
       0.39181929, 0.14709936, 0.6829266 , 0.76684455, 0.86849181])

In [12]:
np.random.rand(4,3)

array([[0.44239399, 0.73967678, 0.35674969],
       [0.30889053, 0.38116778, 0.55299173],
       [0.54094693, 0.22882921, 0.7685108 ],
       [0.16340761, 0.88852547, 0.43281401]])

In [13]:
np.random.randint(0,9,10)

array([7, 4, 8, 0, 8, 6, 6, 3, 4, 0], dtype=int32)

In [14]:
np.random.randint(0,9,(3,4))

array([[6, 4, 6, 6],
       [2, 5, 2, 1],
       [7, 0, 5, 0]], dtype=int32)

# 랜덤 시드 고정

In [ ]:
np.random.seed(1234)
np.random.normal(0,1,(4,3))     # 정규분포 생성 코드

array([[ 0.47143516, -1.19097569,  1.43270697],
       [-0.3126519 , -0.72058873,  0.88716294],
       [ 0.85958841, -0.6365235 ,  0.01569637],
       [-2.24268495,  1.15003572,  0.99194602]])

# 표준정규분포를 따르는 랜덤배열

In [16]:
np.random.randn(10)

array([ 0.95332413, -2.02125482, -0.33407737,  0.00211836,  0.40545341,
        0.28909194,  1.32115819, -1.54690555, -0.20264632, -0.65596934])

In [17]:
np.random.randn(4,3)

array([[ 0.19342138,  0.55343891,  1.31815155],
       [-0.46930528,  0.67555409, -1.81702723],
       [-0.18310854,  1.05896919, -0.39784023],
       [ 0.33743765,  1.04757857,  1.04593826]])