In [1]:
import numpy as np

# 원소의 데이터 타입 변환
## 1. astype

In [2]:
arr1=np.arange(10)
print('원본배열:',arr1)
print('원본배열의 데이터 타입:',arr1.dtype)

원본배열: [0 1 2 3 4 5 6 7 8 9]
원본배열의 데이터 타입: int64


In [3]:
arr2=arr1.astype('float')
print('형변환 후의 배열:',arr2)
print('변환된 배열의 데이터 타입:',arr2.dtype)

형변환 후의 배열: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
변환된 배열의 데이터 타입: float64


In [4]:
arr3=arr1.astype('str')
print('형변환 후의 배열:',arr3)
print('변환된 배열의 데이터 타입:',arr3.dtype)

형변환 후의 배열: ['0' '1' '2' '3' '4' '5' '6' '7' '8' '9']
변환된 배열의 데이터 타입: <U21


## 2. asarray

In [5]:
arr1=np.arange(10,20)
print('원본배열:',arr1)
print('원본배열의 데이터 타입:',arr1.dtype)

원본배열: [10 11 12 13 14 15 16 17 18 19]
원본배열의 데이터 타입: int64


In [6]:
arr2=np.asarray(arr1,dtype='float')
print('형변환 후의 배열:',arr2)
print('변환된 배열의 데이터 타입:',arr2.dtype)

형변환 후의 배열: [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
변환된 배열의 데이터 타입: float64


In [7]:
arr3=np.asarray(arr1,dtype='str')
print('형변환 후의 배열:',arr3)
print('변환된 배열의 데이터 타입:',arr3.dtype)

형변환 후의 배열: ['10' '11' '12' '13' '14' '15' '16' '17' '18' '19']
변환된 배열의 데이터 타입: <U21


# 차원 변환 (reshape)

In [8]:
origin=np.arange(20)
origin

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [9]:
x=origin.reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [10]:
origin=np.array([[0,1,2,3,4],
                [5,6,7,8,9],
                [10,11,12,13,14],
                [15,16,17,18,19]])
origin

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [11]:
y=origin.reshape(20)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
rows,cols=origin.shape
rows,cols

(4, 5)

In [15]:
z=origin.reshape(rows*cols)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
origin=np.array([[0,1,2,3],
                 [4,5,6,7],
                 [8,9,10,11]])
origin

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
x=origin.reshape(-1,1)
x

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [18]:
y=origin.reshape(-1,2)
y

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [19]:
origin=np.arange(12)
origin

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
x=origin.reshape(1,-1)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [21]:
y=origin.reshape(2,-1)
y

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [22]:
origin=np.array([[0,1,2,3,4,5],
                 [6,7,8,9,10,11]])
print(origin)

x=origin.reshape(-1)
x

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])