In [1]:
import numpy as np

In [2]:
myarr=np.array([98,72,80,64,88,65,79,59,81,74])
myarr

array([98, 72, 80, 64, 88, 65, 79, 59, 81, 74])

In [3]:
print('총 도수:',len(myarr))

총 도수: 10


In [4]:
print('최대값:',np.max(myarr))
print('최소값:',np.min(myarr))
print('합계:',np.sum(myarr))

최대값: 98
최소값: 59
합계: 760


In [5]:
print('평균:',np.average(myarr))

평균: 76.0


In [6]:
size=len(myarr)
sorted_arr=np.sort(myarr)
print('정렬:',sorted_arr)

if size%2==0:
    p=(size//2)-1
    q=p+1
    median=(sorted_arr[p]+sorted_arr[q])/2
else:
    p=size//2
    median=sorted_arr[p]

print('중앙값:',median)

정렬: [59 64 65 72 74 79 80 81 88 98]
중앙값: 76.5


In [7]:
print('중앙값:',np.median(myarr))

중앙값: 76.5


In [8]:
x=np.sort(myarr)
n=len(x)
q1_pos=(n-1)*0.25
i=int(np.floor(q1_pos))
f=q1_pos-i

Q1=x[i]+f*(x[i+1]-x[i])
print('직접 계산한 1사분위수 (Q1):',Q1)
print('Numpy로 계산한 1사분위수:',np.quantile(myarr,0.25))

직접 계산한 1사분위수 (Q1): 66.75
Numpy로 계산한 1사분위수: 66.75


In [9]:
x=np.sort(myarr)
n=len(x)
q3_pos=(n-1)*0.75
i=int(np.floor(q3_pos))
f=q3_pos-i

Q3=x[i]+f*(x[i+1]-x[i])
print('직접 계산한 3사분위수 (Q3):',Q3)
print('Numpy로 계산한 3사분위수:',np.quantile(myarr,0.75))

직접 계산한 3사분위수 (Q3): 80.75
Numpy로 계산한 3사분위수: 80.75


In [10]:
print('데이터 구간:', np.max(myarr)-np.min(myarr))

데이터 구간: 39


In [13]:
print('사분위수 구간(IQR):',np.quantile(myarr,0.75)-np.quantile(myarr,0.25))

사분위수 구간(IQR): 14.0


In [14]:
print('분산:',np.var(myarr))
print('표준편차:',np.std(myarr))

분산: 125.2
표준편차: 11.189280584559492


In [17]:
mydata=np.array([[98,72,80,64,88],
                 [65,79,59,81,74]])

s1=np.sum(mydata,axis=0)
print(type(s1))
s1

<class 'numpy.ndarray'>


array([163, 151, 139, 145, 162])

In [18]:
mydata=np.array([[98,72,80,64,88],
                 [65,79,59,81,74]])

s2=np.sum(mydata,axis=1)
print(type(s2))
s2

<class 'numpy.ndarray'>


array([402, 358])